import {StyleSheet} from "react-native";

export const mymenuStyle = StyleSheet.create({
    menu                : {
        flex: 1,
    },
    header              : {
        flex             : 0.03,
        color            : 'white',
        display          : 'flex',
        flexDirection    : 'row',
        justifyContent   : 'space-between',
        alignItems       : 'center',
        paddingHorizontal: 20,
        paddingVertical  : 10,
    },
    headerText          : {
        color: 'white',
    },
    scollableMenuList   : {
        flex: 1,
    },
    typesContainer      : {
        padding      : 20,
        paddingBottom: 0,
        marginTop    : -10,
    },
    typeHeader          : {
        borderRadius  : 20,
        overflow      : "hidden",
        height        : 60,
        alignItems    : 'center',
        justifyContent: 'center',
        position      : 'relative',
        zIndex        : 2,
    },
    type                : {
        width            : '100%',
        display          : 'flex',
        justifyContent   : 'center',
        alignItems       : 'center',
        paddingVertical  : 10,
        paddingHorizontal: 20,
        fontWeight       : 'bold',
        color            : 'white',
        fontSize         : 18,
    },
    itemOutsideContainer: {
        position         : 'relative',
        paddingTop       : 40,
        marginTop        : -40,
        backgroundColor  : 'white',
        zIndex           : 1,
        borderRadius     : 30,
        paddingBottom    : 10,
        paddingHorizontal: 20,
    },
    itemContainer       : {
        width            : '100%',
        paddingHorizontal: 10,
        paddingVertical  : 7,
        backgroundColor  : 'white',
    },
    itemHeader          : {
        display       : 'flex',
        flexDirection : 'row',
        justifyContent: 'space-between',
        alignItems    : 'center',
        flex          : 1,
    },
    itemsLeftContainer  : {
        display       : 'flex',
        flexDirection : 'row',
        gap           : 10,
        justifyContent: "center",
        alignItems    : "center",
    },
    itemTextDesc        : {
        flex: 1,
    },
    itemDescription     : {
        fontSize : 8,
        fontStyle: "italic",
    },
    itemAmountContainer : {
        flex           : 0.4,
        display        : 'flex',
        flexDirection  : 'row',
        justifyContent : 'space-between',
        alignItems     : 'center',
    },
    priceContainer      : {
        flex: 0.5,
    },
    price               : {
        textAlign: 'right',
    },
    deleteBoxContainer  : {
        width         : 50,
        height        : '100%',
        display       : 'flex',
        flexDirection : 'row',
        justifyContent: 'center',
        alignItems    : 'center',
        padding       : 8,
    },
    deleteBox           : {
        // backgroundColor: 'rgba(255,0,0,0.6)',
        borderRadius  : 10,
        justifyContent: 'center',
        alignItems    : 'center',
        width         : '100%',
        height        : '100%',
    },
})